{{/*
Copyright 2019 Nokia

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}
{{ if .Values.danm_webhook.required }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: danm-webhook-deployment
  namespace: kube-system
  labels:
    {{ .Values.kubernetes_component_label }}: danm-webhook
spec:
  selector:
    matchLabels:
      {{ .Values.kubernetes_component_label }}: danm-webhook
  template:
    metadata:
      name: danm-webhook
      labels:
        {{ .Values.kubernetes_component_label }}: danm-webhook
    spec:
      serviceAccountName: danm-webhook
      nodeSelector:
        nodetype: caas_master
      containers:
        - name: danm-webhook
          image: {{ .Values.registry_url }}/{{ .Values.registry_reponame }}/danm-webhook:{{ .Values.danm_webhook.container_version }}
          command: [ "/usr/local/bin/webhook", "-tls-cert-bundle=/etc/webhook/certs/danm_webhook.crt", "-tls-private-key-file=/etc/webhook/certs/danm_webhook.key", "-bind-port={{ .Values.danm_webhook.webhook_target_port }}" ]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        # TODO: make it a secret
        - name: webhook-certs
          hostPath:
            path: /etc/kubernetes/ssl/
{{ end }}
